
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author njbed
 */
public class frmArbol extends javax.swing.JFrame {
    Arbol a1;
    Arbol a2;
    /**
     * Creates new form frmArbol
     */
    public frmArbol() {
        a1 = new Arbol();
        a2 = new Arbol();
        initComponents();
        txtInsertar.requestFocusInWindow();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtInsertar = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnInorden = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        btnPreOrden = new javax.swing.JButton();
        btnPostOrden = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Multiplicar = new javax.swing.JButton();
        btnSumarPares = new javax.swing.JButton();
        btnCantidadElem = new javax.swing.JButton();
        btnMayor = new javax.swing.JButton();
        btnMenor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnContarPares = new javax.swing.JButton();
        btnContarPrimos = new javax.swing.JButton();
        btnMostarPar = new javax.swing.JButton();
        btnMostrarPrimos = new javax.swing.JButton();
        btnAltura = new javax.swing.JButton();
        txtInsertar2 = new javax.swing.JTextField();
        bntInsertar2 = new javax.swing.JButton();
        btnSonIguales = new javax.swing.JButton();
        btnEsLista = new javax.swing.JButton();
        btnMostrarAbuelo = new javax.swing.JButton();
        btnMostrarAncestros = new javax.swing.JButton();
        btnMostrarDesc = new javax.swing.JButton();
        btnMostrarNietos = new javax.swing.JButton();
        btnMostrarNiveles = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInsertar.setText("Insertar");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnInorden.setText("InOrden");
        btnInorden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInordenActionPerformed(evt);
            }
        });

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        btnPreOrden.setText("PreOrden");
        btnPreOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreOrdenActionPerformed(evt);
            }
        });

        btnPostOrden.setText("PostOrden");
        btnPostOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostOrdenActionPerformed(evt);
            }
        });

        jButton1.setText("Sumar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Multiplicar.setText("Multiplicar");
        Multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicarActionPerformed(evt);
            }
        });

        btnSumarPares.setText("SumarPares");
        btnSumarPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarParesActionPerformed(evt);
            }
        });

        btnCantidadElem.setText("cantidad");
        btnCantidadElem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCantidadElemActionPerformed(evt);
            }
        });

        btnMayor.setText("Mayor");
        btnMayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMayorActionPerformed(evt);
            }
        });

        btnMenor.setText("Menor");
        btnMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenorActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnContarPares.setText("contarPar");
        btnContarPares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarParesActionPerformed(evt);
            }
        });

        btnContarPrimos.setText("ContarPrimos");
        btnContarPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContarPrimosActionPerformed(evt);
            }
        });

        btnMostarPar.setText("MostarPar");
        btnMostarPar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostarParActionPerformed(evt);
            }
        });

        btnMostrarPrimos.setText("MostrarPrimos");
        btnMostrarPrimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPrimosActionPerformed(evt);
            }
        });

        btnAltura.setText("Altura");
        btnAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlturaActionPerformed(evt);
            }
        });

        bntInsertar2.setText("Insertar Arbol2");
        bntInsertar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntInsertar2ActionPerformed(evt);
            }
        });

        btnSonIguales.setText("SonIguales");
        btnSonIguales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSonIgualesActionPerformed(evt);
            }
        });

        btnEsLista.setText("esLista");
        btnEsLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsListaActionPerformed(evt);
            }
        });

        btnMostrarAbuelo.setText("MostrarAbuelo");
        btnMostrarAbuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAbueloActionPerformed(evt);
            }
        });

        btnMostrarAncestros.setText("MostrarAnc");
        btnMostrarAncestros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarAncestrosActionPerformed(evt);
            }
        });

        btnMostrarDesc.setText("MostrarDesc");
        btnMostrarDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDescActionPerformed(evt);
            }
        });

        btnMostrarNietos.setText("MostrarNietos");
        btnMostrarNietos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarNietosActionPerformed(evt);
            }
        });

        btnMostrarNiveles.setText("MostrarNiveles");
        btnMostrarNiveles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarNivelesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btnCantidadElem, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMayor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnPreOrden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Multiplicar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnInorden, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSumarPares, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPostOrden)
                            .addComponent(btnMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnMostarPar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMostrarDesc))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnMostrarPrimos)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnMostrarAncestros))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(btnAltura)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnMostrarAbuelo))))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnSonIguales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnMostrarNietos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(bntInsertar2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(txtInsertar2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertar)
                        .addGap(18, 18, 18)
                        .addComponent(btnContarPares)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnContarPrimos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEsLista)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMostrarNiveles)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(bntInsertar2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtInsertar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSonIguales)
                            .addComponent(btnMostrarNietos))
                        .addGap(8, 8, 8)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnInsertar)
                        .addComponent(btnContarPares)
                        .addComponent(btnContarPrimos)
                        .addComponent(btnEsLista))
                    .addComponent(btnMostrarNiveles))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreOrden)
                    .addComponent(btnInorden)
                    .addComponent(btnPostOrden)
                    .addComponent(btnMostarPar)
                    .addComponent(btnMostrarDesc))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnSumarPares)
                        .addComponent(Multiplicar)
                        .addComponent(btnMostrarPrimos)
                        .addComponent(btnMostrarAncestros)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCantidadElem)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMayor)
                        .addComponent(btnMenor)
                        .addComponent(btnAltura)
                        .addComponent(btnMostrarAbuelo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreOrdenActionPerformed
        ta.setText("");
        a1.preOrden(ta);
    }//GEN-LAST:event_btnPreOrdenActionPerformed

    private void btnInordenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInordenActionPerformed
        ta.setText("");
        a1.InOrden(ta);
    }//GEN-LAST:event_btnInordenActionPerformed

    private void btnPostOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostOrdenActionPerformed
        ta.setText("");
        a1.PostOrden(ta);
    }//GEN-LAST:event_btnPostOrdenActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        txtInsertar.requestFocusInWindow();
        int x=Integer.parseInt(txtInsertar.getText());
        a1.insertar(x);
        txtInsertar.setText("");
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ta.setText(Integer.toString(a1.suma()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicarActionPerformed
        ta.setText(Integer.toString(a1.multiplicar()));
    }//GEN-LAST:event_MultiplicarActionPerformed

    private void btnSumarParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarParesActionPerformed
         ta.setText(Integer.toString(a1.sumarPares()));
    }//GEN-LAST:event_btnSumarParesActionPerformed

    private void btnCantidadElemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCantidadElemActionPerformed
        ta.setText(Integer.toString(a1.cantidadElem()));
    }//GEN-LAST:event_btnCantidadElemActionPerformed

    private void btnMayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMayorActionPerformed
        ta.setText(Integer.toString(a1.mayor()));
    }//GEN-LAST:event_btnMayorActionPerformed

    private void btnMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenorActionPerformed
        ta.setText(Integer.toString(a1.menor()));
    }//GEN-LAST:event_btnMenorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int x = Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese nivel"));
        ta.setText(Integer.toString(a1.sumaNivel(x)));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnContarParesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarParesActionPerformed
        ta.setText(Integer.toString(a1.cantidadElemPar()));
    }//GEN-LAST:event_btnContarParesActionPerformed

    private void btnContarPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContarPrimosActionPerformed
         ta.setText(Integer.toString(a1.cantidadElemPrimos()));
    }//GEN-LAST:event_btnContarPrimosActionPerformed

    private void btnMostarParActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostarParActionPerformed
        ta.setText("");
        a1.MostrarPares(ta);
    }//GEN-LAST:event_btnMostarParActionPerformed

    private void btnMostrarPrimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPrimosActionPerformed
        ta.setText("");
        a1.mostrarPrimos(ta);
    }//GEN-LAST:event_btnMostrarPrimosActionPerformed

    private void btnAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlturaActionPerformed
        ta.setText(Integer.toString(a1.altura()));
    }//GEN-LAST:event_btnAlturaActionPerformed

    private void bntInsertar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntInsertar2ActionPerformed
        txtInsertar2.requestFocusInWindow();
        int y=Integer.parseInt(txtInsertar2.getText());
        a2.insertar(y);
        txtInsertar2.setText("");
    }//GEN-LAST:event_bntInsertar2ActionPerformed

    private void btnSonIgualesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSonIgualesActionPerformed
        ta.setText("");
        ta.setText(Boolean.toString(a1.sonIguales(a2.getRaiz())));
    }//GEN-LAST:event_btnSonIgualesActionPerformed

    private void btnEsListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsListaActionPerformed
       ta.setText(Boolean.toString(a1.esLista()));
    }//GEN-LAST:event_btnEsListaActionPerformed

    private void btnMostrarAbueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAbueloActionPerformed
        ta.setText("");
        int x = Integer.parseInt(JOptionPane.showInputDialog(null,"Ingrese x"));
        ta.append(String.valueOf(a1.getAbuelo(x)));
    }//GEN-LAST:event_btnMostrarAbueloActionPerformed

    private void btnMostrarAncestrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarAncestrosActionPerformed
        int x = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese x"));
        a1.mostrarAncestros(x, ta);
    }//GEN-LAST:event_btnMostrarAncestrosActionPerformed

    private void btnMostrarDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDescActionPerformed
        int x = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese x"));
        a1.descendientes(x,ta);
    }//GEN-LAST:event_btnMostrarDescActionPerformed

    private void btnMostrarNietosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarNietosActionPerformed
        int x=Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese x"));
        a1.mostrarNietos(x,ta);
    }//GEN-LAST:event_btnMostrarNietosActionPerformed

    private void btnMostrarNivelesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarNivelesActionPerformed
        a1.mostrarPorNivel(ta);
    }//GEN-LAST:event_btnMostrarNivelesActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmArbol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmArbol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Multiplicar;
    private javax.swing.JButton bntInsertar2;
    private javax.swing.JButton btnAltura;
    private javax.swing.JButton btnCantidadElem;
    private javax.swing.JButton btnContarPares;
    private javax.swing.JButton btnContarPrimos;
    private javax.swing.JButton btnEsLista;
    private javax.swing.JButton btnInorden;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnMayor;
    private javax.swing.JButton btnMenor;
    private javax.swing.JButton btnMostarPar;
    private javax.swing.JButton btnMostrarAbuelo;
    private javax.swing.JButton btnMostrarAncestros;
    private javax.swing.JButton btnMostrarDesc;
    private javax.swing.JButton btnMostrarNietos;
    private javax.swing.JButton btnMostrarNiveles;
    private javax.swing.JButton btnMostrarPrimos;
    private javax.swing.JButton btnPostOrden;
    private javax.swing.JButton btnPreOrden;
    private javax.swing.JButton btnSonIguales;
    private javax.swing.JButton btnSumarPares;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta;
    private javax.swing.JTextField txtInsertar;
    private javax.swing.JTextField txtInsertar2;
    // End of variables declaration//GEN-END:variables
}
